In [1]:
import numpy as np

In [2]:
my_list = np.array([[1,2,3],[4,5,6]])

In [3]:
my_list.shape

(2, 3)

In [4]:
my_list

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
new_array = [1,2,3]

In [6]:
arr = np.array(new_array)

In [7]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
my_arr = range(0,10)

In [11]:
for i in my_arr:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [15]:
np.zeros((3,5)) #tuples! 

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [21]:
np.ones([3,5])

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [24]:
np.linspace(0,11,10)

array([  0.        ,   1.22222222,   2.44444444,   3.66666667,
         4.88888889,   6.11111111,   7.33333333,   8.55555556,
         9.77777778,  11.        ])

In [25]:
np.random.randint(0,100,[3,3])

array([[26, 49,  4],
       [60, 96, 82],
       [35, 60, 36]])

In [27]:
arr = np.random.randint(0, 100, 20)

In [28]:
arr.max()

89

In [29]:
arr.argmax() # index of the max

1

In [30]:
arr.argmin() # index of the min

13

In [31]:
arr.mean()

46.899999999999999

In [32]:
arr

array([52, 89, 82, 45, 15, 54, 20, 29, 13, 62, 84, 68, 22, 11, 34, 58, 74,
       26, 78, 22])

In [33]:
#reshape

In [35]:
arr.reshape(2,5,2)

array([[[52, 89],
        [82, 45],
        [15, 54],
        [20, 29],
        [13, 62]],

       [[84, 68],
        [22, 11],
        [34, 58],
        [74, 26],
        [78, 22]]])

In [36]:
mat = np.arange(0,100).reshape(10,10)

In [37]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [38]:
mat[0, 1]

1

In [39]:
mat[5,3]

53

In [40]:
mat[:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [46]:
mat[1, 2:10]

array([12, 13, 14, 15, 16, 17, 18, 19])

In [47]:
mat[0:3, 0:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [48]:
#filtering
mat[mat>80]

array([81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
       98, 99])