In [1]:
import numpy as np

In [2]:
from sklearn.preprocessing import MinMaxScaler

In [3]:
data = np.random.randint(0,100,(10,2))

In [4]:
data

array([[24, 68],
       [55, 81],
       [54, 24],
       [49, 87],
       [65, 12],
       [78, 16],
       [44, 73],
       [ 6, 91],
       [77, 83],
       [73, 40]])

In [6]:
# scaling data

In [7]:
scaler_model = MinMaxScaler()

In [8]:
scaler_model.fit(data)

C:\Users\Chan\Anaconda3\envs\tfdeeplearning\lib\site-packages\sklearn\utils\validation.py:444: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


MinMaxScaler(copy=True, feature_range=(0, 1))

In [9]:
scaler_model.transform(data)

array([[ 0.25      ,  0.70886076],
       [ 0.68055556,  0.87341772],
       [ 0.66666667,  0.15189873],
       [ 0.59722222,  0.94936709],
       [ 0.81944444,  0.        ],
       [ 1.        ,  0.05063291],
       [ 0.52777778,  0.7721519 ],
       [ 0.        ,  1.        ],
       [ 0.98611111,  0.89873418],
       [ 0.93055556,  0.35443038]])

In [10]:
# one liner
scaler_model.fit_transform(data)

C:\Users\Chan\Anaconda3\envs\tfdeeplearning\lib\site-packages\sklearn\utils\validation.py:444: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


array([[ 0.25      ,  0.70886076],
       [ 0.68055556,  0.87341772],
       [ 0.66666667,  0.15189873],
       [ 0.59722222,  0.94936709],
       [ 0.81944444,  0.        ],
       [ 1.        ,  0.05063291],
       [ 0.52777778,  0.7721519 ],
       [ 0.        ,  1.        ],
       [ 0.98611111,  0.89873418],
       [ 0.93055556,  0.35443038]])

In [11]:
import pandas as pd

In [12]:
my_data = np.random.randint(0, 101, (50,4) )

In [13]:
df = pd.DataFrame(my_data, columns=['f1','f2','f3','label'])

In [14]:
df

f1  f2  f3  label
0   93  55  34     44
1   76  90  76     93
2   65  94  20     25
3   44  40  43     89
4   47  57  77     26
5    3  96  77     68
6   82  21  46     95
7   61   9  44     50
8   31  91  42     22
9   37  45  20     27
10  58  49  32     84
11  70  38  52     28
12  21  58  75     93
13  96  99  37     55
14  66  94  38     47
15  70  66  37     50
16  27  87  42     71
17   7  53  13     79
18  56  29  83     53
19  51  63  11     74
20  37  51  27     13
21  69  71  13     18
22   2  91  60     64
23  31  78  10     42
24   2  87  19     71
25   6   9  80     42
26  92  53  18     58
27  36   8  48     87
28  33  17  99     14
29  91  20  23     70
30  77  51  70     52
31  42  88  58     19
32  90  72  67      7
33  25  69  35     47
34  90  51  42     50
35  17  24  26     51
36   2  20  29     78
37  51  69   2     88
38  62  52   7     73
39  93  66   5     69
40  96  49  52     26
41  84  52  59     46
42  75  66  57      1
43   1  40   8     96
44  23   3  29     35
45  69   3  98     72
46  97  62  37     24
47  39  70  20      7
48  59  72  13     67
49  89  96  55     67

In [16]:
X = df[['f1','f2','f3']]

In [17]:
y = df['label']

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

In [21]:
X_train.shape

(35, 3)

In [22]:
y_train.shape

(35,)